config/routes.rb
Chapter3::Application.routes.draw do
 
 resources :users
 
 resources :articles do
    resources :comments
    resources :critics
 end

 resources :critics

 resources :sessions, only: [:new, :create, :destroy]

 root to: 'static_pages#home'

 
 match '/home', to: 'static_pages#home'
 match '/help', to: 'static_pages#help'
 match '/about', to: 'static_pages#about'
 match '/contact', to: 'static_pages#contact'

 match '/signup',  to: 'users#new'

 match '/signin', to: 'sessions#new'
 match '/signout', to: 'sessions#destroy', via: :delete

 match '/km',  to: 'static_pages#km'

 match '/pm',  to: 'static_pages#pm'

 match '/time',  to: 'static_pages#time'
 match '/ecommerce',  to: 'static_pages#ecommerce'
 match '/product',  to: 'static_pages#product'
 match '/mobile',  to: 'static_pages#mobile'
 match '/movie',  to: 'static_pages#movie'
 match '/logic',  to: 'static_pages#logic'
 match '/read',  to: 'static_pages#read'
 match '/life',  to: 'static_pages#life'
 
match '/web',  to: 'static_pages#web'
match '/java',  to: 'static_pages#java'
match '/ruby',  to: 'static_pages#ruby'
match '/data',  to: 'static_pages#data'
match '/searchresult',  to: 'static_pages#searchresult'
match '/job',  to: 'static_pages#job'
match '/job_show',  to: 'static_pages#job_show'
match '/seven_show',  to: 'static_pages#seven_show'
match '/work_show',  to: 'static_pages#work_show'
match '/programmer_show',  to: 'static_pages#programmer_show'
match '/fun_show',  to: 'static_pages#fun_show'
match '/new_show',  to: 'static_pages#new_show'
match '/old_show',  to: 'static_pages#old_show'

match '/admin',  to: 'static_pages#admin'

end

app/views/shared/_about.html.erb
<div class="row">
	

	<div class="span6">
	    <table class="table table-striped">
	   		<tr>
	   			<td>开发环境：<td>
	   			<td>Ubuntu13.04、 sqlite3<td>	
	   		</tr>
	   		<tr>
	   			<td>开发工具：<td>
	   			<td>sublime2<td>	
	   		</tr>

	   		<tr>
	   			<td>开发语言：<td>
	   			<td>ruby1.9.3、 rails3.2.13、 bootstrap<td>	
	   		</tr>

	   	


	    </table>

	</div>

	<div div class="span4" align="center">
		<section>
		<img src="assets/rails.png">
	    </section>

	</div>

	

</div>

app/views/shared/_article.html.erb
 <section>
 	       <%= render 'shared/success' %>   	
    	   <p align="center"><strong><%=@article.title%></strong><p>
		   <p align="center">
		   	   <small>标签:<%=@article.tag%> &nbsp; &nbsp; &nbsp; 
		   	   	     新建时间:<%=@article.created_at%>&nbsp; &nbsp; &nbsp;
		   	   	     文章作者:<%= @article_user.name%>
		   	   </small>
		   </p>

		   		    
		    </br>
		   <%=raw @article.content%>
			</br>	
 </section>				

app/views/shared/_critic.html.erb
 <%= form_for(@critic) do |f| %>
  <div>
      <p>
         <small>输入您的评论评论:</small> <%= f.kindeditor :content, :width => 600, :height => 300, :langType => 'en' %> 
      </p>
  </div>
  
         <%= hidden_field_tag(:article_id, @article.id) %>
  
  <div class="actions">
         <%= f.submit  :评论提交, class: "btn btn-large btn-primary" %>
  </div>
<% end %>  

app/views/shared/_ecommerces.html.erb
<ol>
	<%@ecommerces.each do |ecommerce|%>
		<li><%=link_to ecommerce.title,article_path(ecommerce)%>
		</li>
	<%end%>
</ol>

app/views/shared/_fun_shows.html.erb
<ol>
	<%@fun_shows.each do |fun_show|%>
		<li><%=link_to fun_show.title,article_path(fun_show)%>
		</li>
	<%end%>
</ol>
<%=paginate @fun_shows, :theme => 'twitter-bootstrap' %>

app/views/shared/_jss.html.erb
<ul>
<%@jss.each do |js|%>
	<li><%=link_to js.title,article_path(js)%></br>
		<%=js.content%></li>
<%end%>
</ul>

app/views/shared/_pms.html.erb
<ol>
<%@pms.each do |pm|%>
	<li><%=link_to pm.title,article_path(pm)%>
	</li>
<%end%>
</ol>

app/views/shared/_publish_article.html.erb
<section>
    <%= link_to '发布知识',new_article_path,class: "btn btn-large btn-primary" %>	
</section>

app/views/shared/_reads.html.erb
<ol>
	<%@reads.each do |read|%>
		<li><%=link_to read.title,article_path(read)%>
		</li>
	<%end%>
</ol>

app/views/shared/_seven_more.html.erb
<section>
		 <div class="zouqi"><strong>走七活动</strong></div>
		 <div class="zouqimore"><%=link_to "查看更多",seven_show_path%></div>
</section>

app/views/shared/_user_information.html.erb
<aside class="span4">
		<section>
			<p><strong><%= link_to @user.name,@user %></strong></p>
			<p><small><%=@user.email%></small></p>
		</section>
</aside>

app/views/shared/_webs.html.erb
<ol>
<%@webs.each do |web|%>
	<li><%=link_to web.title,article_path(web)%></br>
		<%=raw web.content%></li>
<%end%>
</ol>

app/views/shared/_work_shows.html.erb
<ol>	        
	<%@work_shows.each do |work_show|%>
		<li><%=link_to work_show.title,article_path(work_show)%>
		</li>
	<%end%>
</ol>
<%=paginate @work_shows, :theme => 'twitter-bootstrap' %> 

app/views/shared/_works_more.html.erb
<section>
		 <div class="zouqi"><strong>就业信息</strong></div>
		 <div class="zouqimore"><%=link_to "查看更多",work_show_path%></div>
</section>