config/routes.rb
Chapter3::Application.routes.draw do
 
 resources :users
 
 resources :articles do
    resources :comments
    resources :critics
 end

 resources :critics

 resources :sessions, only: [:new, :create, :destroy]

 root to: 'static_pages#home'

 
 match '/home', to: 'static_pages#home'
 match '/help', to: 'static_pages#help'
 match '/about', to: 'static_pages#about'
 match '/contact', to: 'static_pages#contact'

 match '/signup',  to: 'users#new'

 match '/signin', to: 'sessions#new'
 match '/signout', to: 'sessions#destroy', via: :delete

 match '/km',  to: 'static_pages#km'

 match '/pm',  to: 'static_pages#pm'

 match '/time',  to: 'static_pages#time'
 match '/ecommerce',  to: 'static_pages#ecommerce'
 match '/product',  to: 'static_pages#product'
 match '/mobile',  to: 'static_pages#mobile'
 match '/movie',  to: 'static_pages#movie'
 match '/logic',  to: 'static_pages#logic'
 match '/read',  to: 'static_pages#read'
 match '/life',  to: 'static_pages#life'
 
match '/web',  to: 'static_pages#web'
match '/java',  to: 'static_pages#java'
match '/ruby',  to: 'static_pages#ruby'
match '/data',  to: 'static_pages#data'
match '/searchresult',  to: 'static_pages#searchresult'
match '/job',  to: 'static_pages#job'
match '/job_show',  to: 'static_pages#job_show'
match '/seven_show',  to: 'static_pages#seven_show'
match '/work_show',  to: 'static_pages#work_show'
match '/programmer_show',  to: 'static_pages#programmer_show'
match '/fun_show',  to: 'static_pages#fun_show'
match '/new_show',  to: 'static_pages#new_show'
match '/old_show',  to: 'static_pages#old_show'

match '/admin',  to: 'static_pages#admin'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<nav>
		<ul>
			
			<li><small><%= link_to "关于本站", about_path %></small></li>
			
		</ul>
	</nav>
</footer>


app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "CIMS知识共享平台", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">       
          <% if signed_in? %>

            <% if current_user.admin? %>
                <li><%= link_to "管理员", admin_path %></li>  
            <% end %>
            



            <li><%= link_to "用户圈", users_path %></li>
            <li><%= link_to "发布文章", articles_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                账户 <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "资料显示", current_user %></li>
                <li><%= link_to "设置更新", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "退出", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>         
                <li><%= link_to "用户登陆", signin_path%></li>               
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>



<title><%=full_title(yield(:title))%></title>
<%= stylesheet_link_tag "application", media: "all" %>
<%= javascript_include_tag "application" %>
<%= csrf_meta_tags %>
<%= render 'layouts/shim' %>
</head>
	<body>
	<%= render 'layouts/header' %>
	<div class="container">


	<%= yield %>
    <%= render 'layouts/footer' %>
	</div>
	</body>
</html>